// export const baseURL = "http://localhost:3100";
 export const baseURL = "http://10.8.64.64:3100";

export const HTTP_METHOD = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE"
}

export const INDEX_ELECTRICITY = {
     GET_INDEX_ELECTRICITY_REQUEST: "GET_INDEX_ELECTRICITY_REQUEST",
     GET_INDEX_ELECTRICITY_SUCCESS: "GET_INDEX_ELECTRICITY_SUCCESS",
     GET_INDEX_ELECTRICITY_FAILURE: "GET_INDEX_ELECTRICITY_FAILURE",
}
