// export const baseURL = "http://localhost:3100";
export const baseURL = "http://10.8.64.64:8081";

export const HTTP_METHOD = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE"
}

export const INDEX_ELECTRICITY = {
    GET_INDEX_ELECTRICITY_REQUEST: "GET_INDEX_ELECTRICITY_REQUEST",
    GET_INDEX_ELECTRICITY_SUCCESS: "GET_INDEX_ELECTRICITY_SUCCESS",
    GET_INDEX_ELECTRICITY_FAILURE: "GET_INDEX_ELECTRICITY_FAILURE",
}

export const NOTIFICATION = {
    GET_NOTIFY_REQUEST: 'GET_NOTIFY_REQUEST',
    GET_NOTIFY_SUCCESS: 'GET_NOTIFY_SUCCESS',
    GET_NOTIFY_FAILURE: 'GET_NOTIFY_FAILURE',
    TURN_OFF_NOTIFY: 'TURN_OFF_NOTIFY'
}

export const SETUP_TIME_TO_CALL_ACTION = {
    UPDATE_TIME_TO_CALL_REQUEST: "UPDATE_TIME_TO_CALL_REQUEST",
}
